import { EXPLORER_BASE_URL as DEFAULT_EXPLORER_BASE_URL } from "@fairco.in/core";
import type { NetworkType } from "@fairco.in/core";

/**
 * Typed environment reader for the Oxy Pay Gateway backend.
 *
 * Every value is validated and defaulted explicitly — no `process.env.X!`,
 * no magic numbers scattered through the code. `loadConfig` is pure over its
 * `env` argument so it can be exercised in isolation; `config` is the process
 * singleton built from `process.env` at import time.
 */

const DEFAULT_PORT = 3001;
const DEFAULT_NETWORK: NetworkType = "mainnet";
// Conventional local dev target; overridden by MONGODB_URI in every real env.
const DEFAULT_MONGODB_URI = "mongodb://localhost:27017/oxypay";
// The hosted checkout page's host (F2.2/F2.3) — see `2026-07-19-fase2-checkout-links.md`.
const DEFAULT_CHECKOUT_BASE_URL = "https://checkout.oxy.so";
// The SAME literal fallback the shared `oxyClient` singleton itself is built
// with (`@oxyhq/core`'s `OXY_API_URL = process.env.OXY_API_URL || 'https://api.oxy.so'`)
// — not re-exported from that package's public entry, so mirrored here rather
// than imported, matching the convention every other Oxy backend
// (`Mention/packages/backend`, `oxy-ship`, …) already uses for the same constant.
const DEFAULT_OXY_API_URL = "https://api.oxy.so";

export interface AppConfig {
  /** Base URL of the FairCoin block explorer (no trailing slash). */
  explorerBaseUrl: string;
  /** Network the gateway operates on (`mainnet` | `testnet`). */
  network: NetworkType;
  /** MongoDB connection string. */
  mongodbUri: string;
  /**
   * PostgreSQL connection string, or `undefined` where none is configured.
   *
   * Optional for exactly as long as no route reads Postgres. `db/postgres.ts`
   * refuses to open a pool without it, with a named error rather than a `!`, so
   * an unconfigured deployment fails at the call that needed the database
   * instead of at boot — which is what keeps this change safe to deploy ahead
   * of the task definition carrying `DATABASE_URL`. The change that moves the
   * first route to Postgres makes it REQUIRED here and calls
   * `connectPostgres()` from `server.ts`, so a misconfigured task crash-loops
   * rather than serving half a service.
   */
  databaseUrl: string | undefined;
  /** HTTP port the API listens on. */
  port: number;
  /**
   * Exact browser origins allowed to open a realtime Socket.io connection AND
   * (F2.5) to call the REST API cross-origin — both `createGateway`'s Socket.io
   * `cors.origin` check and `createOxyCors({ appOrigins })` in `server.ts` read
   * this same list (comma-separated `OXY_PAY_ALLOWED_ORIGINS`). It exists
   * because `createOxyCors`'s built-in Oxy-family allowlist only trusts
   * ONE-LABEL `*.oxy.so` subdomains — a two-label host like
   * `dashboard.pay.oxy.so` must be listed here explicitly. Requests with no
   * `Origin` (native apps / server-to-server) are always allowed; an arbitrary
   * browser origin is NEVER reflected — it must be listed here. REST routes
   * remain gated by their own auth (service token / Oxy user bearer /
   * `client_secret`) regardless of CORS.
   */
  allowedOrigins: string[];
  /**
   * HMAC secret used to verify Oxy service-token JWTs presented by merchants
   * (`Authorization: Bearer <token>`). MUST equal the value oxy-api signs
   * service tokens with (`ACCESS_TOKEN_SECRET` in `OxyHQServices/packages/api`)
   * — a cross-service SHARED secret, provisioned out of band (SSM), not
   * generated by the Gateway. `undefined` when not yet provisioned: every real
   * service-token request then 403s (`SERVICE_TOKEN_NOT_CONFIGURED`) instead of
   * silently accepting an unverified token.
   */
  serviceJwtSecret: string | undefined;
  /**
   * Base URL of the hosted checkout page (no trailing slash) — used to build
   * `PaymentLink.url` (`/l/<id>`) and `CheckoutSession.url` (`/c/<id>`).
   */
  checkoutBaseUrl: string;
  /**
   * Base URL of oxy-api (no trailing slash) — `services/appMembership.ts`
   * forwards the dashboard caller's Oxy bearer here (`GET
   * /applications/:applicationId`) to delegate `/v1/dashboard/*` authorization
   * to oxy-api's own Application RBAC (zero RBAC duplication). Reads the SAME
   * `OXY_API_URL` env var (and same `https://api.oxy.so` default) the shared
   * `oxyClient` singleton itself was constructed with, so the two never drift.
   */
  oxyApiUrl: string;
}

function readOrigins(raw: string | undefined): string[] {
  if (raw === undefined) return [];
  return raw
    .split(",")
    .map((origin) => origin.trim())
    .filter((origin) => origin !== "");
}

function readNetwork(raw: string | undefined): NetworkType {
  if (raw === undefined || raw.trim() === "") return DEFAULT_NETWORK;
  const value = raw.trim();
  if (value === "mainnet" || value === "testnet") return value;
  throw new Error(
    `OXYPAY_NETWORK must be "mainnet" or "testnet", received "${raw}"`,
  );
}

function readPort(raw: string | undefined): number {
  if (raw === undefined || raw.trim() === "") return DEFAULT_PORT;
  const value = Number(raw);
  if (!Number.isInteger(value) || value <= 0) {
    throw new Error(`PORT must be a positive integer, received "${raw}"`);
  }
  return value;
}

function readNonEmpty(raw: string | undefined, fallback: string): string {
  if (raw === undefined) return fallback;
  const value = raw.trim();
  return value === "" ? fallback : value;
}

function readOptional(raw: string | undefined): string | undefined {
  if (raw === undefined) return undefined;
  const value = raw.trim();
  return value === "" ? undefined : value;
}

export function loadConfig(
  env: Record<string, string | undefined> = process.env,
): AppConfig {
  return {
    explorerBaseUrl: readNonEmpty(
      env.EXPLORER_BASE_URL,
      DEFAULT_EXPLORER_BASE_URL,
    ),
    network: readNetwork(env.OXYPAY_NETWORK),
    mongodbUri: readNonEmpty(env.MONGODB_URI, DEFAULT_MONGODB_URI),
    databaseUrl: readOptional(env.DATABASE_URL),
    port: readPort(env.PORT),
    allowedOrigins: readOrigins(env.OXY_PAY_ALLOWED_ORIGINS),
    serviceJwtSecret: readOptional(env.OXY_ACCESS_TOKEN_SECRET),
    checkoutBaseUrl: readNonEmpty(env.OXY_PAY_CHECKOUT_BASE_URL, DEFAULT_CHECKOUT_BASE_URL),
    oxyApiUrl: readNonEmpty(env.OXY_API_URL, DEFAULT_OXY_API_URL),
  };
}

export const config = loadConfig();
