import { EXPLORER_BASE_URL as DEFAULT_EXPLORER_BASE_URL } from "@fairco.in/core";
import type { NetworkType } from "@fairco.in/core";

/**
 * Typed environment reader for the Oxy Pay Gateway backend.
 *
 * Every value is validated and defaulted explicitly — no `process.env.X!`,
 * no magic numbers scattered through the code. `loadConfig` is pure over its
 * `env` argument so it can be exercised in isolation; `config` is the process
 * singleton built from `process.env` at import time.
 */

const DEFAULT_PORT = 3001;
const DEFAULT_NETWORK: NetworkType = "mainnet";
// Conventional local dev target; overridden by MONGODB_URI in every real env.
const DEFAULT_MONGODB_URI = "mongodb://localhost:27017/oxypay";

export interface AppConfig {
  /** Base URL of the FairCoin block explorer (no trailing slash). */
  explorerBaseUrl: string;
  /** Network the gateway operates on (`mainnet` | `testnet`). */
  network: NetworkType;
  /** MongoDB connection string. */
  mongodbUri: string;
  /** HTTP port the API listens on. */
  port: number;
  /**
   * Exact browser origins allowed to open a realtime Socket.io connection
   * (comma-separated `OXY_PAY_ALLOWED_ORIGINS`). Requests with no `Origin`
   * (native apps / server-to-server) are always allowed; an arbitrary browser
   * origin is NEVER reflected — it must be listed here. The connection is still
   * gated by `authSocket()` and per-intent `client_secret`.
   */
  allowedOrigins: string[];
  /**
   * HMAC secret used to verify Oxy service-token JWTs presented by merchants
   * (`Authorization: Bearer <token>`). MUST equal the value oxy-api signs
   * service tokens with (`ACCESS_TOKEN_SECRET` in `OxyHQServices/packages/api`)
   * — a cross-service SHARED secret, provisioned out of band (SSM), not
   * generated by the Gateway. `undefined` when not yet provisioned: every real
   * service-token request then 403s (`SERVICE_TOKEN_NOT_CONFIGURED`) instead of
   * silently accepting an unverified token.
   */
  serviceJwtSecret: string | undefined;
}

function readOrigins(raw: string | undefined): string[] {
  if (raw === undefined) return [];
  return raw
    .split(",")
    .map((origin) => origin.trim())
    .filter((origin) => origin !== "");
}

function readNetwork(raw: string | undefined): NetworkType {
  if (raw === undefined || raw.trim() === "") return DEFAULT_NETWORK;
  const value = raw.trim();
  if (value === "mainnet" || value === "testnet") return value;
  throw new Error(
    `OXYPAY_NETWORK must be "mainnet" or "testnet", received "${raw}"`,
  );
}

function readPort(raw: string | undefined): number {
  if (raw === undefined || raw.trim() === "") return DEFAULT_PORT;
  const value = Number(raw);
  if (!Number.isInteger(value) || value <= 0) {
    throw new Error(`PORT must be a positive integer, received "${raw}"`);
  }
  return value;
}

function readNonEmpty(raw: string | undefined, fallback: string): string {
  if (raw === undefined) return fallback;
  const value = raw.trim();
  return value === "" ? fallback : value;
}

function readOptional(raw: string | undefined): string | undefined {
  if (raw === undefined) return undefined;
  const value = raw.trim();
  return value === "" ? undefined : value;
}

export function loadConfig(
  env: Record<string, string | undefined> = process.env,
): AppConfig {
  return {
    explorerBaseUrl: readNonEmpty(
      env.EXPLORER_BASE_URL,
      DEFAULT_EXPLORER_BASE_URL,
    ),
    network: readNetwork(env.OXYPAY_NETWORK),
    mongodbUri: readNonEmpty(env.MONGODB_URI, DEFAULT_MONGODB_URI),
    port: readPort(env.PORT),
    allowedOrigins: readOrigins(env.OXY_PAY_ALLOWED_ORIGINS),
    serviceJwtSecret: readOptional(env.OXY_ACCESS_TOKEN_SECRET),
  };
}

export const config = loadConfig();
